# Generated by Django 3.2.8 on 2022-03-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Sender',
        ),
        migrations.AddField(
            model_name='message',
            name='SenderIsCustomer',
            field=models.BooleanField(default=None),
        ),
    ]
