# Generated by Django 3.2.8 on 2022-03-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220307_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='SenderIsCustomer',
            field=models.BooleanField(default=False),
        ),
    ]
