# Generated by Django 3.2.8 on 2022-09-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='accept_agreemnt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leads',
            name='first_payment',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='first_payment_due',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='next_payment',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='next_payment_due',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
