# Generated by Django 3.2.8 on 2022-09-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20220914_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='testing_appp',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
