# Generated by Django 3.2.8 on 2022-09-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_leads_accept_agreemnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='first_payment',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='first_payment_due',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='next_payment',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='next_payment_due',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='testing_appp',
        ),
    ]
