# Generated by Django 3.2.8 on 2022-09-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20220914_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(max_length=100000)),
                ('amount', models.FloatField(blank=True, default=None, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
