# Generated by Django 3.2.8 on 2022-09-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_refundagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundagreement',
            name='date_of_customer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
